#This will build the fork.c program and create a executable "fork"

CC = gcc
RM = rm -rf
SOURCE = fork.c
TARGET = fork

all: $(TARGET)

$(TARGET): $(SOURCE)
	$(CC) -o $(TARGET) $(SOURCE)

clean:
	$(RM) fork
	
